version: '3.6'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://localhost:9092,DOCKER://kafka:9094
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092,DOCKER://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  schema-registry:
    build:
      context: ./docker/schema-registry
      dockerfile: Dockerfile
    command: >-
      sh -c "java -jar schema-registry-0.0.1-SNAPSHOT.jar"
    ports:
      - "8990:8990"
